### ISSUE TITLE
cannot start dev server

### ISSUE THREAD

**Issue by t-cool** [tanykazy/lifegames#1]
I cannot start dev server by npm run server.
The error message is as follows:

```
$ npm run serve

> Lifegame@0.1.0 serve /lifegames/Vue.js/Lifegame
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: No valid exports main found for 'lifegames/Vue.js/Lifegame/node_modules/colorette'
Error: No valid exports main found for '/ifegames/Vue.js/Lifegame/node_modules/colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Vue.js/Lifegame/node_modules/autoprefixer/lib/autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Lifegame@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Lifegame@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-07-25T08_29_28_008Z-debug.log
$ 
```

**Comment by t-cool** [comment]
If I update node.js to v14.5, this problem got solved.
